#! /bin/sh
	
echo -n "Stopping $DESC: $NAME"
start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE \
	--exec $DAEMON
if [ "$?" -ne 0 ]; then
	return $?
fi
if [ "$TABLE" -ge 0 ] && [ "$VIRT" != "yes" ]; then
	set +e
	if [ -e /proc/mediaproxy/control ]; then
		echo "del $TABLE" > /proc/mediaproxy/control 2>/dev/null
	fi
	if [ -e /proc/rtpengine/control ]; then
		echo "del $TABLE" > /proc/rtpengine/control 2>/dev/null
	fi
	
	iptables -D INPUT -j mediaproxy 2> /dev/null
	iptables -D rtpengine -p udp -j RTPENGINE --id "$TABLE" 2>/dev/null
	ip6tables -D INPUT -j mediaproxy 2> /dev/null
	ip6tables -D rtpengine -p udp -j RTPENGINE --id "$TABLE" 2>/dev/null
	rmmod xt_RTPENGINE 2>/dev/null
	set -e
fi
exit 0

